[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.10,<3.14"
pip = ">=26.0.1,<27"
wheel = ">=0.46.3,<0.47"
hatchling = ">=1.29.0,<2"
cmake = ">=4.3.0,<5"

[feature.dev.dependencies]
pytest = ">=9.0.2,<10"
pytest-cov = ">=7.0.0,<8"
pytest-qt = "*"
tox = "*"
mkdocs-material = "*"
pdoc = "*"

[feature.dev.pypi-dependencies]
napari = { version = ">=0.6.0, <0.7", extras = ["all"] }

[tasks]
build = "pip install -e ."
test = "pytest -v"
build-doc = "pip install -e . & pdoc epicure -o docs/api & mkdocs build"
go = "pip install -e . & napari"

[environments]
default = { features = ["dev"], solve-group = "default" }
